import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#0B0F1A',
  },

  orb1: {
    position: 'absolute',
    top: -100,
    left: -100,
    width: width * 0.9,
    height: width * 0.9,
    borderRadius: width * 0.45,
    backgroundColor: '#6750A4',
  },
  orb2: {
    position: 'absolute',
    bottom: -120,
    right: -80,
    width: width * 0.75,
    height: width * 0.75,
    borderRadius: width * 0.375,
    backgroundColor: '#22D3EE',
  },

  // ── Header ────────────────────────────────────────────────────────────────
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: 'rgba(11,15,26,0.88)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.08)',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#5E35B1',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(99,102,241,0.4)',
    overflow: 'hidden',
  },
  headerAvatarText: {
    fontSize: 14,
    fontWeight: '800',
    color: 'white',
  },
  headerBrand: {
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: -0.5,
    color: '#8B5CF6',
  },
  headerBrandAccent: {
    color: '#22D3EE',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  headerBadgeText: {
    fontSize: 9,
    fontWeight: '700',
    color: 'white',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  headerSettingsBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerNotifBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notifDot: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#F87171',
  },

  // ── Scroll ────────────────────────────────────────────────────────────────
  scroll: {
    paddingTop: 24,
    paddingBottom: 24,
  },

  // ── Welcome ───────────────────────────────────────────────────────────────
  welcomeSection: {
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  welcomeTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: 'white',
    letterSpacing: -0.8,
    marginBottom: 6,
  },
  welcomeSub: {
    fontSize: 14,
    color: 'rgba(148,163,184,0.8)',
    lineHeight: 21,
    fontWeight: '500',
  },
  welcomeSubAccent: {
    color: '#818CF8',
    fontWeight: '700',
  },
  welcomeBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
  },

  // ── Audit hero card ────────────────────────────────────────────────────────
  auditHeroCard: {
    borderRadius: 24,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(167,139,250,0.2)',
    backgroundColor: 'rgba(17,24,39,0.8)',
    marginBottom: 12,
    shadowColor: '#7C3AED',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 8,
  },
  auditHeroInner: {
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  auditHeroTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: 'rgba(167,139,250,0.15)',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(167,139,250,0.25)',
  },
  auditHeroTagText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#A78BFA',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  auditHeroTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: 'white',
    letterSpacing: -0.5,
    lineHeight: 28,
  },
  auditHeroSub: {
    fontSize: 12,
    color: 'rgba(148,163,184,0.7)',
  },
  auditHeroBtn: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  auditHeroBtnText: {
    fontSize: 12,
    fontWeight: '800',
    color: 'white',
    letterSpacing: 0.5,
  },
  auditScoreRing: {
    width: 88,
    height: 88,
    alignItems: 'center',
    justifyContent: 'center',
  },
  auditScoreCenter: {
    position: 'absolute',
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  auditScoreNum: {
    fontSize: 26,
    fontWeight: '900',
    color: 'white',
    letterSpacing: -1,
    lineHeight: 30,
  },
  auditScoreLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: 'rgba(167,139,250,0.8)',
    marginBottom: 3,
  },
  auditActionsSection: {
    paddingHorizontal: 4,
    gap: 8,
  },
  auditActionsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  auditActionsTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: 'white',
    letterSpacing: -0.2,
  },
  auditActionsPriority: {
    fontSize: 10,
    fontWeight: '700',
    color: '#A78BFA',
    letterSpacing: 0.5,
  },
  auditActionCard: {
    backgroundColor: 'rgba(17,24,39,0.75)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  auditActionIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  auditActionText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    color: 'rgba(230,224,233,0.9)',
    lineHeight: 18,
  },

  // ── Daily challenge card ───────────────────────────────────────────────────
  dailyChallengeWrap: {
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  dailyChallengeCard: {
    borderRadius: 28,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    shadowColor: '#6366F1',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 24,
    elevation: 10,
  },
  dailyChallengeInner: {
    padding: 24,
  },
  dailyTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  dailyTag: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: 'rgba(99,102,241,0.2)',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(99,102,241,0.3)',
    marginBottom: 12,
    alignSelf: 'flex-start',
  },
  dailyTagText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#A5B4FC',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  dailyChallengeTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: 'white',
    letterSpacing: -0.6,
    lineHeight: 32,
    maxWidth: width - 130,
  },
  dailyTimeCard: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 14,
    padding: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    minWidth: 72,
  },
  dailyTimeLabel: {
    fontSize: 8,
    fontWeight: '700',
    color: 'rgba(148,163,184,0.6)',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  dailyTimeValue: {
    fontSize: 20,
    fontWeight: '800',
    color: 'white',
    letterSpacing: -0.5,
  },
  dailyChallengeDesc: {
    fontSize: 14,
    color: 'rgba(226,232,240,0.85)',
    lineHeight: 22,
    marginBottom: 24,
  },
  dailyChallengeDescAccent: {
    color: '#818CF8',
    fontWeight: '700',
  },
  dailyActions: {
    flexDirection: 'row',
    gap: 10,
  },
  practiceNowBtn: {
    flex: 1,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#6366F1',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 14,
    elevation: 8,
  },
  practiceNowBtnInner: {
    paddingVertical: 14,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  practiceNowBtnText: {
    fontSize: 12,
    fontWeight: '800',
    color: 'white',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  remindBtn: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  remindBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.8)',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },

  // ── Job readiness card ─────────────────────────────────────────────────────
  jobReadinessWrap: {
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  jobReadinessCard: {
    backgroundColor: 'rgba(17,24,39,0.8)',
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    padding: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 8,
  },
  jobReadinessTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: 'white',
    marginBottom: 24,
  },
  circleWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    position: 'relative',
  },
  circleCenter: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  circleScore: {
    fontSize: 48,
    fontWeight: '900',
    color: 'white',
    letterSpacing: -2,
    lineHeight: 52,
  },
  circleEliteBadge: {
    fontSize: 10,
    fontWeight: '800',
    color: '#818CF8',
    letterSpacing: 3,
    textTransform: 'uppercase',
    marginTop: 4,
  },
  jobReadinessSub: {
    fontSize: 13,
    color: 'rgba(148,163,184,0.75)',
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 10,
  },
  jobReadinessSubBold: {
    color: 'white',
    fontWeight: '700',
  },

  // ── Quick actions ─────────────────────────────────────────────────────────
  quickActionsSection: {
    paddingHorizontal: 20,
    marginBottom: 28,
    gap: 12,
  },
  quickActionCard: {
    backgroundColor: 'rgba(17,24,39,0.7)',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    overflow: 'hidden',
  },
  quickActionIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickActionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: 'white',
    letterSpacing: -0.2,
    marginBottom: 3,
  },
  quickActionSub: {
    fontSize: 12,
    color: 'rgba(100,116,139,0.8)',
  },
  quickActionChevron: {
    marginLeft: 'auto' as any,
  },

  // ── Section header ────────────────────────────────────────────────────────
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: 'white',
    letterSpacing: -0.3,
  },
  sectionViewAll: {
    fontSize: 10,
    fontWeight: '800',
    color: '#818CF8',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },

  // ── News cards ────────────────────────────────────────────────────────────
  newsSection: {
    paddingHorizontal: 20,
    gap: 12,
    marginBottom: 28,
  },
  newsCard: {
    backgroundColor: 'rgba(17,24,39,0.75)',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    overflow: 'hidden',
  },
  newsThumb: {
    width: 80,
    height: 80,
    borderRadius: 14,
    overflow: 'hidden',
    flexShrink: 0,
  },
  newsContent: {
    flex: 1,
  },
  newsCategoryText: {
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 5,
  },
  newsTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: 'white',
    letterSpacing: -0.1,
    lineHeight: 20,
    marginBottom: 8,
  },
  newsMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  newsMetaText: {
    fontSize: 11,
    color: 'rgba(100,116,139,0.8)',
    fontWeight: '500',
  },
  newsMetaDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: 'rgba(100,116,139,0.5)',
  },
  newsTrendText: {
    fontSize: 11,
    fontWeight: '700',
  },

  // ── AI Suggestions ────────────────────────────────────────────────────────
  aiSuggestionsSection: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  aiSuggestionsCard: {
    backgroundColor: 'rgba(99,102,241,0.07)',
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(99,102,241,0.2)',
    padding: 24,
    overflow: 'hidden',
  },
  aiSuggestionsGlow: {
    position: 'absolute',
    top: -60,
    right: -60,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(99,102,241,0.1)',
  },
  aiSuggestionsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 24,
  },
  aiIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: 'rgba(99,102,241,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  aiSuggestionsTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: 'white',
    letterSpacing: -0.3,
  },
  aiSuggestion: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
    marginBottom: 20,
  },
  aiSuggestionDotWrap: {
    paddingTop: 6,
  },
  aiSuggestionDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  aiSuggestionText: {
    flex: 1,
    fontSize: 14,
    color: 'rgba(203,196,210,0.85)',
    lineHeight: 22,
  },
  aiSuggestionBold: {
    color: 'white',
    fontWeight: '700',
  },
  aiSuggestionsFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.06)',
  },
  aiSyncRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  aiSyncDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: '#22C55E',
  },
  aiSyncText: {
    fontSize: 11,
    color: 'rgba(100,116,139,0.8)',
    fontWeight: '500',
  },

  // ── Bottom nav ────────────────────────────────────────────────────────────
  bottomNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingTop: 10,
    paddingBottom: 8,
    backgroundColor: 'rgba(11,15,26,0.95)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.1)',
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
    paddingHorizontal: 16,
    borderRadius: 14,
    gap: 3,
  },
  navItemActive: {
    backgroundColor: 'rgba(99,102,241,0.2)',
  },
  navLabel: {
    fontSize: 9,
    fontWeight: '700',
    color: 'rgba(100,116,139,0.7)',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  navLabelActive: {
    color: '#A5B4FC',
  },
});
