import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#0B0F1A',
  },

  orb1: {
    position: 'absolute',
    top: -80,
    right: -100,
    width: width * 0.85,
    height: width * 0.85,
    borderRadius: width * 0.425,
    backgroundColor: '#6366F1',
  },
  orb2: {
    position: 'absolute',
    bottom: -100,
    left: -80,
    width: width * 0.7,
    height: width * 0.7,
    borderRadius: width * 0.35,
    backgroundColor: '#22D3EE',
  },

  // ── Header ────────────────────────────────────────────────────────────────
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: 'rgba(17,24,39,0.88)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.08)',
  },
  headerBrand: {
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: -0.5,
    color: '#8B5CF6',
  },
  headerBrandAccent: {
    color: '#22D3EE',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  notifDot: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#F87171',
  },
  headerAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#5E35B1',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(99,102,241,0.4)',
  },
  headerAvatarText: {
    fontSize: 12,
    fontWeight: '800',
    color: 'white',
  },

  // ── Scroll ────────────────────────────────────────────────────────────────
  scroll: {
    paddingTop: 24,
    paddingBottom: 24,
  },

  // ── Hero section ──────────────────────────────────────────────────────────
  heroSection: {
    paddingHorizontal: 20,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 10,
  },
  heroTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: 'white',
    letterSpacing: -0.8,
    marginBottom: 4,
  },
  heroSub: {
    fontSize: 13,
    color: 'rgba(148,163,184,0.75)',
    lineHeight: 20,
  },
  matchBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: 'rgba(34,211,238,0.1)',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(34,211,238,0.22)',
  },
  matchBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#22D3EE',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },

  // ── Filter bar ────────────────────────────────────────────────────────────
  filterBar: {
    marginHorizontal: 20,
    marginBottom: 24,
    backgroundColor: 'rgba(17,24,39,0.85)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    padding: 14,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    alignItems: 'center',
  },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: 'rgba(13,18,31,0.9)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    flex: 1,
    minWidth: 140,
  },
  filterChipText: {
    fontSize: 12,
    color: 'rgba(226,232,240,0.85)',
    fontWeight: '500',
    flex: 1,
  },
  toggleChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: 'rgba(13,18,31,0.9)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  toggleLabel: {
    fontSize: 12,
    color: 'rgba(148,163,184,0.75)',
    fontWeight: '500',
  },
  toggleTrack: {
    width: 38,
    height: 20,
    borderRadius: 10,
    justifyContent: 'center',
    paddingHorizontal: 3,
  },
  toggleThumb: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: 'white',
  },
  resetBtn: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  resetBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: 'rgba(148,163,184,0.6)',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },

  // ── Job cards ─────────────────────────────────────────────────────────────
  jobsList: {
    paddingHorizontal: 20,
    gap: 16,
  },
  jobCard: {
    backgroundColor: 'rgba(17,24,39,0.85)',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    padding: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  jobCardTopLine: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 1,
  },

  // Card header
  jobCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 16,
    gap: 10,
  },
  jobCardLeft: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    flex: 1,
  },
  jobIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 14,
    backgroundColor: 'rgba(13,18,31,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  jobTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: 'white',
    letterSpacing: -0.2,
    marginBottom: 3,
    lineHeight: 22,
    flexShrink: 1,
  },
  jobCompany: {
    fontSize: 12,
    color: 'rgba(148,163,184,0.7)',
    lineHeight: 17,
  },
  matchScoreWrap: {
    alignItems: 'flex-end',
    flexShrink: 0,
  },
  matchScore: {
    fontSize: 30,
    fontWeight: '900',
    letterSpacing: -1,
    lineHeight: 34,
  },
  matchScoreLabel: {
    fontSize: 8,
    fontWeight: '700',
    color: 'rgba(100,116,139,0.7)',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginTop: 2,
  },

  // Tags
  tagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 14,
  },
  tag: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  tagText: {
    fontSize: 10,
    fontWeight: '700',
    color: 'rgba(226,232,240,0.75)',
    letterSpacing: 0.5,
  },

  // AI Insight panel
  insightPanel: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 14,
    marginBottom: 16,
    overflow: 'hidden',
  },
  insightHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  insightTitle: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  insightText: {
    fontSize: 13,
    color: 'rgba(148,163,184,0.8)',
    lineHeight: 20,
  },
  insightHighlight: {
    fontWeight: '700',
  },

  // Footer actions
  jobCardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  footerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  recruiterStack: {
    flexDirection: 'row',
  },
  recruiterBubble: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: 'rgba(17,24,39,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: -8,
  },
  recruiterCount: {
    fontSize: 9,
    fontWeight: '800',
    color: 'white',
  },
  footerMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  footerMetaText: {
    fontSize: 12,
    color: 'rgba(100,116,139,0.8)',
  },
  directHireRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  directHireText: {
    fontSize: 12,
    color: 'rgba(148,163,184,0.7)',
  },
  footerBtns: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  quickApplyBtn: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  quickApplyText: {
    fontSize: 10,
    fontWeight: '800',
    color: 'rgba(226,232,240,0.75)',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  optimizeBtn: {
    borderRadius: 12,
    overflow: 'hidden',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
  },
  optimizeBtnInner: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  optimizeBtnText: {
    fontSize: 10,
    fontWeight: '800',
    color: 'white',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },

  // ── Main tab switcher ─────────────────────────────────────────────────────
  mainTabBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 10,
    gap: 8,
    backgroundColor: 'rgba(11,15,26,0.9)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.06)',
  },
  mainTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 9,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  mainTabActive: {
    backgroundColor: '#22D3EE',
    borderColor: '#22D3EE',
  },
  mainTabText: {
    fontSize: 13,
    fontWeight: '700',
    color: 'rgba(148,163,184,0.6)',
    letterSpacing: 0.3,
  },
  mainTabTextActive: {
    color: '#0B0F1A',
  },

  // ── Live jobs ─────────────────────────────────────────────────────────────
  liveJobCard: {
    backgroundColor: 'rgba(17,24,39,0.75)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(99,102,241,0.15)',
    padding: 16,
    overflow: 'hidden',
  },
  liveJobHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    marginBottom: 10,
  },
  liveJobIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: 'rgba(99,102,241,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(99,102,241,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  liveJobTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: 'rgba(226,232,240,0.9)',
    letterSpacing: -0.1,
    marginBottom: 2,
    lineHeight: 20,
  },
  liveJobCompany: {
    fontSize: 11,
    color: 'rgba(100,116,139,0.7)',
  },
  liveJobSourceBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: 'rgba(99,102,241,0.12)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(99,102,241,0.2)',
    flexShrink: 0,
  },
  liveJobSourceText: {
    fontSize: 9,
    fontWeight: '700',
    color: 'rgba(99,102,241,0.85)',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  liveJobFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  liveJobApplyText: {
    fontSize: 11,
    color: 'rgba(100,116,139,0.55)',
  },

  // ── Live divider ──────────────────────────────────────────────────────────
  liveDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 20,
    marginVertical: 20,
    gap: 10,
  },
  liveDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  liveDividerBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: 'rgba(99,102,241,0.1)',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(99,102,241,0.2)',
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#6366F1',
  },
  liveDividerText: {
    fontSize: 10,
    fontWeight: '700',
    color: 'rgba(99,102,241,0.85)',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },

  // ── Company tabs ──────────────────────────────────────────────────────────
  companyTabBar: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginBottom: 20,
    backgroundColor: 'rgba(17,24,39,0.85)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
    overflow: 'hidden',
  },
  companyTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingVertical: 11,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  companyTabText: {
    fontSize: 12,
    fontWeight: '700',
    color: 'rgba(100,116,139,0.55)',
    letterSpacing: 0.3,
  },

  // ── Companies section ──────────────────────────────────────────────────────
  companiesSectionHeader: {
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  companiesSectionTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: 'white',
    letterSpacing: -0.5,
    marginBottom: 3,
  },
  companiesSectionSub: {
    fontSize: 12,
    color: 'rgba(148,163,184,0.6)',
  },
  companiesList: {
    paddingHorizontal: 20,
    gap: 14,
    paddingBottom: 24,
  },

  // ── Company card ──────────────────────────────────────────────────────────
  companyCard: {
    backgroundColor: 'rgba(17,24,39,0.85)',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    padding: 18,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 6,
  },
  companyCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 10,
  },
  companyInitialBadge: {
    width: 46,
    height: 46,
    borderRadius: 13,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  companyInitialText: {
    fontSize: 20,
    fontWeight: '900',
  },
  companyName: {
    fontSize: 16,
    fontWeight: '800',
    color: 'white',
    letterSpacing: -0.2,
    marginBottom: 2,
  },
  companyMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  companyMetaText: {
    fontSize: 11,
    color: 'rgba(100,116,139,0.65)',
  },
  batchBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: 'rgba(251,176,64,0.12)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(251,176,64,0.3)',
  },
  batchBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#FBB040',
    letterSpacing: 0.5,
  },
  companyDescription: {
    fontSize: 12,
    color: 'rgba(148,163,184,0.65)',
    lineHeight: 18,
    marginBottom: 12,
  },
  companyTagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 14,
  },
  companyTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 9,
    paddingVertical: 4,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  companyTagText: {
    fontSize: 10,
    fontWeight: '600',
    color: 'rgba(148,163,184,0.7)',
    letterSpacing: 0.3,
    textTransform: 'capitalize',
  },
  companyActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  coldEmailBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: 'rgba(139,92,246,0.1)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(139,92,246,0.25)',
  },
  coldEmailBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#A78BFA',
    letterSpacing: 0.3,
  },
  visitBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },

  // ── Loading / error states ────────────────────────────────────────────────
  loadingWrap: {
    alignItems: 'center',
    paddingVertical: 48,
    gap: 12,
  },
  loadingText: {
    fontSize: 13,
    color: 'rgba(100,116,139,0.6)',
  },
  errorWrap: {
    alignItems: 'center',
    paddingVertical: 48,
    gap: 12,
  },
  errorText: {
    fontSize: 13,
    color: 'rgba(100,116,139,0.6)',
    textAlign: 'center',
    paddingHorizontal: 20,
  },
  retryBtn: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    backgroundColor: 'rgba(99,102,241,0.15)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(99,102,241,0.3)',
  },
  retryBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6366F1',
    letterSpacing: 0.5,
  },

  // ── Job snippet text ──────────────────────────────────────────────────────
  jobSnippet: {
    fontSize: 12,
    color: 'rgba(148,163,184,0.6)',
    lineHeight: 18,
    marginBottom: 12,
  },

  // ── Source chips row ──────────────────────────────────────────────────────
  sourceChipsRow: {
    paddingHorizontal: 20,
    paddingBottom: 14,
    gap: 8,
    flexDirection: 'row',
  },
  sourceChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
  },
  sourceChipDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
  },
  sourceChipText: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.3,
    textTransform: 'capitalize',
  },
  sourceChipCount: {
    fontSize: 9,
    fontWeight: '600',
    color: 'rgba(100,116,139,0.6)',
  },

  // ── Load more ─────────────────────────────────────────────────────────────
  loadMoreWrap: {
    alignItems: 'center',
    paddingVertical: 16,
  },
  loadMoreBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: 'rgba(99,102,241,0.08)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(99,102,241,0.25)',
  },
  loadMoreBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: 'rgba(99,102,241,0.85)',
    letterSpacing: 0.3,
  },
  endOfListText: {
    fontSize: 12,
    color: 'rgba(100,116,139,0.45)',
    textAlign: 'center',
  },

  // ── Company detail modal ───────────────────────────────────────────────────
  detailOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  detailSheet: {
    backgroundColor: '#111827',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderTopWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    maxHeight: height * 0.88,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  detailHero: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 20,
    paddingHorizontal: 4,
    borderRadius: 16,
    marginBottom: 4,
  },
  detailInitialBadge: {
    width: 58,
    height: 58,
    borderRadius: 16,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  detailInitialText: {
    fontSize: 26,
    fontWeight: '900',
  },
  detailCompanyName: {
    fontSize: 22,
    fontWeight: '800',
    color: 'white',
    letterSpacing: -0.5,
    marginBottom: 4,
  },
  batchBadgeInline: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: 'rgba(251,176,64,0.12)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(251,176,64,0.3)',
  },
  detailCloseBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  detailSection: {
    marginBottom: 20,
  },
  detailSectionTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: 'rgba(100,116,139,0.6)',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  detailDescriptionText: {
    fontSize: 14,
    color: 'rgba(148,163,184,0.8)',
    lineHeight: 22,
  },
  infoRowsWrap: {
    gap: 10,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  infoRowLabel: {
    fontSize: 12,
    color: 'rgba(100,116,139,0.7)',
    width: 100,
    flexShrink: 0,
  },
  infoRowValue: {
    fontSize: 13,
    fontWeight: '600',
    color: 'rgba(226,232,240,0.85)',
    flex: 1,
    textTransform: 'capitalize',
  },
  detailLinksRow: {
    flexDirection: 'row',
    gap: 10,
  },
  detailLinkBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  detailLinkText: {
    fontSize: 12,
    color: 'rgba(148,163,184,0.7)',
    fontWeight: '500',
  },
  detailCtaRow: {
    marginBottom: 8,
  },
  detailColdEmailBtn: {
    borderRadius: 14,
    overflow: 'hidden',
  },
  detailColdEmailBtnInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    paddingHorizontal: 20,
  },
  detailColdEmailBtnText: {
    fontSize: 14,
    fontWeight: '800',
    color: 'white',
    letterSpacing: 0.3,
  },

  // ── Cold email composer modal ──────────────────────────────────────────────
  composerOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  composerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.65)',
  },
  composerSheet: {
    backgroundColor: '#111827',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderTopWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    maxHeight: height * 0.92,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  sheetHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignSelf: 'center',
    marginBottom: 16,
  },
  composerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  composerTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: 'white',
    letterSpacing: -0.3,
  },
  composerSub: {
    fontSize: 12,
    color: 'rgba(148,163,184,0.6)',
    marginTop: 2,
  },
  composerCloseBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fieldLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: 'rgba(100,116,139,0.7)',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 6,
    marginTop: 14,
  },
  fieldLabelOptional: {
    fontSize: 10,
    fontWeight: '500',
    color: 'rgba(100,116,139,0.45)',
    textTransform: 'none',
    letterSpacing: 0,
  },
  fieldInput: {
    backgroundColor: 'rgba(13,18,31,0.9)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 14,
    color: 'rgba(226,232,240,0.9)',
  },
  fieldInputMultiline: {
    minHeight: 160,
    paddingTop: 12,
  },
  mailtoBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 20,
    paddingVertical: 13,
    paddingHorizontal: 20,
    backgroundColor: 'rgba(99,102,241,0.15)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(99,102,241,0.3)',
  },
  mailtoBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: 'white',
  },
  hirelithEmailToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: 'rgba(139,92,246,0.06)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(139,92,246,0.2)',
  },
  hirelithEmailToggleText: {
    fontSize: 13,
    color: '#A78BFA',
    fontWeight: '600',
    flex: 1,
  },
  gmailFieldsWrap: {
    marginTop: 12,
    padding: 16,
    backgroundColor: 'rgba(139,92,246,0.05)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(139,92,246,0.15)',
  },
  gmailNote: {
    fontSize: 11,
    color: 'rgba(100,116,139,0.6)',
    lineHeight: 16,
    marginBottom: 4,
  },
  sendBackendBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 16,
    paddingVertical: 13,
    paddingHorizontal: 20,
    backgroundColor: '#7C3AED',
    borderRadius: 14,
  },
  sendBackendBtnText: {
    fontSize: 14,
    fontWeight: '800',
    color: 'white',
    letterSpacing: 0.3,
  },

  // ── Sender profile card (inside composer) ─────────────────────────────────
  senderCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(139,92,246,0.06)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(139,92,246,0.18)',
    padding: 14,
    marginBottom: 20,
    gap: 10,
  },
  senderCardLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  senderAvatar: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  senderAvatarText: {
    fontSize: 20,
    fontWeight: '800',
  },
  senderName: {
    fontSize: 15,
    fontWeight: '700',
    color: 'white',
    letterSpacing: -0.1,
    marginBottom: 2,
  },
  senderHeadline: {
    fontSize: 11,
    color: 'rgba(148,163,184,0.65)',
    marginBottom: 6,
  },
  senderBadgeRow: {
    flexDirection: 'row',
    gap: 6,
  },
  senderBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(52,211,153,0.3)',
    backgroundColor: 'rgba(52,211,153,0.06)',
  },
  senderBadgeText: {
    fontSize: 10,
    fontWeight: '600',
  },
  senderCardAutoTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 7,
    paddingVertical: 4,
    backgroundColor: 'rgba(139,92,246,0.12)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(139,92,246,0.25)',
    flexShrink: 0,
  },
  senderCardAutoText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#A78BFA',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },

  // ── Cold email composer — new 5-step UI ───────────────────────────────────
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 14,
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: 'rgba(239,68,68,0.1)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.25)',
  },
  errorBannerText: {
    fontSize: 12,
    color: '#F87171',
    flex: 1,
    lineHeight: 18,
  },
  toneRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  toneChip: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 9,
    borderRadius: 12,
    backgroundColor: 'rgba(13,18,31,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  toneChipActive: {
    backgroundColor: 'rgba(139,92,246,0.18)',
    borderColor: '#8B5CF6',
  },
  toneChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: 'rgba(100,116,139,0.7)',
    textTransform: 'capitalize',
  },
  toneChipTextActive: {
    color: '#C4B5FD',
    fontWeight: '700',
  },
  generateBtn: {
    borderRadius: 14,
    overflow: 'hidden',
    marginTop: 20,
    shadowColor: '#7C3AED',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 6,
  },
  generateBtnInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    paddingHorizontal: 20,
  },
  generateBtnText: {
    fontSize: 14,
    fontWeight: '800',
    color: 'white',
    letterSpacing: 0.3,
  },
  generatingWrap: {
    alignItems: 'center',
    paddingVertical: 40,
    gap: 14,
  },
  generatingOrb: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: 'rgba(139,92,246,0.18)',
    borderWidth: 2,
    borderColor: 'rgba(139,92,246,0.4)',
  },
  generatingTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: 'white',
    letterSpacing: -0.2,
  },
  generatingHint: {
    fontSize: 12,
    color: 'rgba(148,163,184,0.6)',
    textAlign: 'center',
    lineHeight: 18,
    paddingHorizontal: 20,
  },
  previewMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 16,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  previewMetaText: {
    fontSize: 12,
    color: 'rgba(148,163,184,0.7)',
    flex: 1,
  },
  previewActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 20,
  },
  regenerateBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 13,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  regenerateBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: 'rgba(148,163,184,0.8)',
    letterSpacing: 0.2,
  },
  sendBtn: {
    flex: 2,
    borderRadius: 14,
    overflow: 'hidden',
    shadowColor: '#7C3AED',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 6,
  },
  sendBtnInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 13,
    paddingHorizontal: 20,
  },
  sendBtnText: {
    fontSize: 14,
    fontWeight: '800',
    color: 'white',
    letterSpacing: 0.3,
  },
  doneIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: 'rgba(52,211,153,0.18)',
    borderWidth: 2,
    borderColor: 'rgba(52,211,153,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  doneCloseBtn: {
    marginTop: 8,
    paddingVertical: 12,
    paddingHorizontal: 32,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  doneCloseBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: 'rgba(148,163,184,0.8)',
    letterSpacing: 0.3,
  },

  // ── Shimmer strip ─────────────────────────────────────────────────────────
  shimmerStrip: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 80,
    zIndex: 2,
  },

  // ── Bottom nav ────────────────────────────────────────────────────────────
  bottomNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingTop: 10,
    paddingBottom: 8,
    backgroundColor: 'rgba(17,24,39,0.95)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.1)',
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 12,
    gap: 3,
    minWidth: 56,
  },
  navItemActive: {
    backgroundColor: 'rgba(34,211,238,0.12)',
  },
  navLabel: {
    fontSize: 9,
    fontWeight: '700',
    color: 'rgba(100,116,139,0.6)',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  navLabelActive: {
    color: '#22D3EE',
  },
});
